import { render, screen, fireEvent } from "@testing-library/react";
import "@testing-library/jest-dom";
import { useInterview } from "../../src/context/InterviewContext";
import { mockMatchMedia, Wrapper } from "../helpers";

function CtxReader() { const ctx = useInterview(); return <pre data-testid="ctx">{JSON.stringify(ctx)}</pre>; }

describe("InterviewContext", () => {
  beforeEach(() => mockMatchMedia());

  it("provides defaults", () => { render(<CtxReader />, { wrapper: Wrapper }); const d = JSON.parse(screen.getByTestId("ctx").textContent); expect(d.screen).toBe("landing"); expect(d.candidate.name).toBe(""); expect(d.answers).toEqual([]); expect(d.startedAt).toBeNull(); });
  it("throws outside provider", () => { jest.spyOn(console, "error").mockImplementation(()=>{}); expect(() => render(<CtxReader />)).toThrow(); console.error.mockRestore(); });
  it("setScreen works", () => { function C(){const{screen:s,setScreen}=useInterview();return<><span data-testid="s">{s}</span><button onClick={()=>setScreen("details")}>go</button></>} render(<C/>,{wrapper:Wrapper}); fireEvent.click(screen.getByText("go")); expect(screen.getByTestId("s")).toHaveTextContent("details"); });
  it("toggleTheme works", () => { function C(){const{theme,toggleTheme}=useInterview();return<><span data-testid="t">{theme}</span><button onClick={toggleTheme}>t</button></>} render(<C/>,{wrapper:Wrapper}); const i=screen.getByTestId("t").textContent; fireEvent.click(screen.getByText("t")); expect(screen.getByTestId("t").textContent).not.toBe(i); });
  it("updateCandidate merges", () => { function C(){const{candidate,updateCandidate}=useInterview();return<><span data-testid="n">{candidate.name}</span><span data-testid="r">{candidate.role}</span><button onClick={()=>updateCandidate({name:"A"})}>set</button></>} render(<C/>,{wrapper:Wrapper}); fireEvent.click(screen.getByText("set")); expect(screen.getByTestId("n")).toHaveTextContent("A"); expect(screen.getByTestId("r")).toHaveTextContent("Frontend Engineer"); });
  it("recordAnswer adds and updates", () => { function C(){const{answers,recordAnswer}=useInterview();return<><span data-testid="a">{JSON.stringify(answers)}</span><button onClick={()=>recordAnswer(1,"answered",80)}>a1</button><button onClick={()=>recordAnswer(1,"answered",95)}>u1</button></>} render(<C/>,{wrapper:Wrapper}); fireEvent.click(screen.getByText("a1")); expect(JSON.parse(screen.getByTestId("a").textContent)).toHaveLength(1); fireEvent.click(screen.getByText("u1")); const d=JSON.parse(screen.getByTestId("a").textContent); expect(d).toHaveLength(1); expect(d[0].confidence).toBe(95); });
  it("start/endInterview set timestamps", () => { function C(){const{startedAt,endedAt,startInterview,endInterview}=useInterview();return<><span data-testid="s">{String(startedAt)}</span><span data-testid="e">{String(endedAt)}</span><button onClick={startInterview}>s</button><button onClick={endInterview}>e</button></>} render(<C/>,{wrapper:Wrapper}); expect(screen.getByTestId("s")).toHaveTextContent("null"); fireEvent.click(screen.getByText("s")); expect(screen.getByTestId("s").textContent).not.toBe("null"); fireEvent.click(screen.getByText("e")); expect(screen.getByTestId("e").textContent).not.toBe("null"); });
  it("resetAll works", () => { function C(){const ctx=useInterview();return<><span data-testid="s">{ctx.screen}</span><button onClick={()=>ctx.setScreen("summary")}>d</button><button onClick={ctx.resetAll}>r</button></>} render(<C/>,{wrapper:Wrapper}); fireEvent.click(screen.getByText("d")); fireEvent.click(screen.getByText("r")); expect(screen.getByTestId("s")).toHaveTextContent("landing"); });
  it("setCodingCode/Language work", () => { function C(){const{codingCode,codingLanguage,setCodingCode,setCodingLanguage}=useInterview();return<><span data-testid="c">{codingCode}</span><span data-testid="l">{codingLanguage}</span><button onClick={()=>setCodingCode("x")}>sc</button><button onClick={()=>setCodingLanguage("Python")}>sl</button></>} render(<C/>,{wrapper:Wrapper}); fireEvent.click(screen.getByText("sc")); expect(screen.getByTestId("c")).toHaveTextContent("x"); fireEvent.click(screen.getByText("sl")); expect(screen.getByTestId("l")).toHaveTextContent("Python"); });
});
